### ISSUE TITLE
Different versions of TF.js between library user & consumer cause instanceof check fail error

### ISSUE THREAD

**Issue by aman-tiwari** [PAIR-code/federated-learning#33]
If construct a `tf.Model` with a different instantiation of Tensorflow.js I get the error `User-defined optimizer must be an instance of tf.Optimizer`, as the library constructs its own [`SGDOptimizer`](src/common/index.ts#L250), which fails the instanceof check within the `tf.Model` constructed by the library consumer's version of Tensorflow.js

I think this is due to the instanceof check in https://github.com/tensorflow/tfjs-layers/blob/de37e29133e2bc11defd3f5931e9e6afcacb7004/src/engine/training.ts#L745 failing.

**Comment by aman-tiwari** [comment]
https://github.com/tensorflow/tfjs/issues/592

**Comment by asross** [comment]
Although the tfjs issue is still outstanding, the problem in this repo should be resolved by https://github.com/PAIR-code/federated-learning/pull/38.
